#Paisaje
import turtle
window = turtle.Screen()
flecha = turtle.Turtle()
flecha.penup()

def suelo(longitud):
    flecha.speed(20)
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#20EF0F')
    flecha.goto(-480,100)
    flecha.pendown()
    for i in range(4):
        flecha.forward(longitud)
        flecha.right(90)
    flecha.end_fill()
    flecha.penup()
    flecha.home()
    
def cielo(longitud):
    flecha.speed(20)
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#07F7EF')
    flecha.goto(-480,1100)
    flecha.pendown()
    for i in range(4):
        flecha.forward(longitud)
        flecha.right(90)
    flecha.end_fill()
    flecha.penup()
    flecha.home()

def casa(longitud):
    flecha.speed(10)
    flecha.pendown()
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#F1F107')
    for i in range(4):
        flecha.forward(longitud)
        flecha.right(90)
    for i in range(1):
        flecha.end_fill()
        flecha.begin_fill()
        flecha.color('black','red')
        flecha.right(-60)
        flecha.forward(longitud)
        flecha.right(60)
        flecha.forward(1)
        flecha.right(60)
        flecha.forward(longitud)
    for i in range(1):
        flecha.right(-60)
        flecha.forward(2*(longitud))
        flecha.right(-90)
        flecha.forward((87/100)*longitud)
        flecha.right(-90)
        flecha.forward((5/2)*longitud)
    for i in range(1):
        flecha.right(-120)
        flecha.forward(longitud+1)
        flecha.end_fill()
        flecha.begin_fill()
        flecha.color('black','#F1F107')
        flecha.right(-60)
        flecha.forward(2*longitud)
        flecha.right(90)
        flecha.forward(longitud)
        flecha.right(90)
        flecha.forward(2*longitud)
        flecha.end_fill()
        flecha.right(0)
        flecha.forward((2/6)*longitud)
    for i in range(1):
        flecha.begin_fill()
        flecha.color('black','#784212')
        flecha.right(90)
        flecha.forward((3/8)*longitud)
        flecha.right(-90)
        flecha.forward((1/3)*longitud)
        flecha.right(-90)
        flecha.forward((3/8)*longitud)
        flecha.end_fill()
        flecha.begin_fill()
        flecha.color('black','#839192')
        flecha.right(0)
        flecha.forward((3)*longitud)
        flecha.right(-90)
        flecha.forward((1/3)*longitud)
        flecha.right(-90)
        flecha.forward((3)*longitud)
        flecha.end_fill()
        flecha.penup()
        flecha.home()
        
def casa1(longitud):
    flecha.speed(10)
    flecha.pendown()
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#F1F107')
    for i in range(4):
        flecha.forward(longitud)
        flecha.right(90)
    for i in range(1):
        flecha.end_fill()
        flecha.begin_fill()
        flecha.color('black','red')
        flecha.right(-60)
        flecha.forward(longitud)
        flecha.right(60)
        flecha.forward(1)
        flecha.right(60)
        flecha.forward(longitud)
        flecha.end_fill()
        flecha.right(30)
        flecha.forward(longitud)
        flecha.right(90)
        flecha.forward((2/6)*longitud)
    for i in range(1):
        flecha.begin_fill()
        flecha.color('black','#784212')
        flecha.right(90)
        flecha.forward((3/8)*longitud)
        flecha.right(-90)
        flecha.forward((1/3)*longitud)
        flecha.right(-90)
        flecha.forward((3/8)*longitud)
        flecha.end_fill()
        flecha.begin_fill()
        flecha.color('black','#839192')
        flecha.right(60)
        flecha.forward((5)*longitud)
        flecha.right(-90)
        flecha.forward((1/6)*longitud)
        flecha.right(-90)
        flecha.forward(((5)*longitud)+15)
        flecha.end_fill()
        flecha.penup()
        flecha.home()
    
def estrella(longitud):
    flecha.speed(10)
    flecha.pendown()
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#F7F707')
    for i in range(5):
        flecha.right(144)
        flecha.forward(longitud)
    flecha.end_fill()
    flecha.penup()
    flecha.home()

def ventana(longitud):
    flecha.speed(10)
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#2EB3D0')
    flecha.pendown()
    for i in range(4):
        flecha.right(90)
        flecha.forward(longitud)
    flecha.end_fill()
    flecha.penup()
    flecha.home()

def circulo(longitud):
    flecha.speed(10)
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#2EB3D0')
    flecha.pendown()
    flecha.circle(longitud)
    flecha.end_fill()
    flecha.penup()
    flecha.home()

def arbol(longitud):
    flecha.speed(10)
    flecha.heading()
    flecha.begin_fill()
    flecha.color('black','#784212')
    flecha.pendown()
    for i in range(1):
        flecha.right(90)
        flecha.forward(3*longitud)
        flecha.right(90)
        flecha.forward(longitud)
        flecha.right(90)
        flecha.forward(3*longitud)
        flecha.right(90)
        flecha.forward(longitud)
        flecha.end_fill()
        flecha.right(0)
        flecha.forward(-(longitud/2))
        flecha.right(90)
        flecha.forward(longitud/2)
        flecha.right(270)
        
        flecha.begin_fill()
        flecha.color('black','#1BB413')
        flecha.pendown()
        flecha.circle(longitud)
    flecha.end_fill()
    flecha.penup()
    flecha.home()
            
suelo(1000)
cielo(1000)
flecha.goto(340,130)
casa1(50)
flecha.goto(385,120)
ventana(15)
flecha.goto(360,120)
ventana(15)

flecha.goto(-400,5)
casa(200)
flecha.goto(-320,-10)
ventana(70)
flecha.goto(-220,-10)
ventana(70)
flecha.goto(-100,-10)
ventana(70)
flecha.goto(20,-10)
ventana(70)
flecha.goto(150,-10)
ventana(70)
flecha.goto(-100,-100)
ventana(70)
flecha.goto(20,-100)
ventana(70)
flecha.goto(150,-100)
ventana(70)

flecha.goto(-300,20)
circulo(40)
flecha.goto(375,350)
estrella(100)
flecha.goto(-400,-150)
arbol(60)
flecha.goto(-150,-150)
arbol(60)
flecha.goto(320,100)
arbol(15)
flecha.goto(400,100)
arbol(15)
flecha.goto(-450,100)
arbol(15)
flecha.goto(360,-150)
arbol(60)
